apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sujaygowdag333/kube-demo-frontend:latest
          # env:
          #   - name: AUTH_ADDRESS
          #     # value: "10.99.1.1"
          #     # OR USE BELOW as Domain Names (core dns)
          #     value: "auth-service.default"
